/**
 * Standard HTML Report Template
 * This template ensures consistent structure for AI-generated medical reports
 */

export interface ReportTemplateData {
  fileName?: string;
  analysisDate?: string;
  fileType?: string;
}

/**
 * Gets the standard HTML report template
 * AI should fill in the content sections while maintaining the header and footer structure
 */
export function getReportTemplate(data?: ReportTemplateData): string {
  const fileName = data?.fileName || 'Medical File';
  const analysisDate = data?.analysisDate || new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });
  const fileType = data?.fileType || 'Document';

  return `
<!-- Report Header -->
<header class="bg-blue text-white py-6 px-6 rounded-t-lg shadow-md">
  <div class="flex flex-col md:flex-row md:items-center md:justify-between">
    <div>
      <h1 class="text-3xl font-bold mb-2">Medical Analysis Report</h1>
      <p class="text-blue-100 text-sm">AI-Powered Diagnostic Analysis</p>
    </div>
    <div class="mt-4 md:mt-0 text-right">
      <p class="text-sm text-blue-100">File: <span class="font-semibold">${escapeHtml(fileName)}</span></p>
      <p class="text-sm text-blue-100">Type: <span class="font-semibold">${escapeHtml(fileType)}</span></p>
      <p class="text-sm text-blue-100">Date: <span class="font-semibold">${escapeHtml(analysisDate)}</span></p>
    </div>
  </div>
</header>

<!-- Report Content Container -->
<main class="bg-white dark:bg-slate-50 p-6 rounded-b-lg">
  <!-- AI will insert analysis content here -->
  <!-- Replace this comment with structured sections like: -->
  <!-- 
  <section class="mb-6">
    <h2 class="text-2xl font-semibold text-gray-800 dark:text-gray-900 mb-4 border-b-2 border-blue-500 pb-2">Findings</h2>
    <div class="space-y-4">
      <!-- Analysis content -->
    </div>
  </section>
  -->
  
  <!-- Content placeholder - AI will replace this -->
  <div id="analysis-content" class="space-y-6">
    <!-- AI-generated content goes here -->
  </div>
</main>

<!-- Report Footer -->
<footer class="bg-gray-100 dark:bg-slate-800 text-gray-700 dark:text-gray-300 py-4 px-6 rounded-lg mt-4 border-t-2 border-gray-300 dark:border-slate-600">
  <div class="flex flex-col md:flex-row md:items-center md:justify-between text-sm">
    <div class="mb-2 md:mb-0">
      <p class="font-semibold">Generated by AI Medical Assistant</p>
      <p class="text-xs text-gray-600 dark:text-gray-400 mt-1">
        This analysis is for informational purposes only and should not replace professional medical consultation.
      </p>
    </div>
    <div class="text-right">
      <p class="text-xs text-gray-600 dark:text-gray-400">
        Report ID: <span class="font-mono">${generateReportId()}</span>
      </p>
      <p class="text-xs text-gray-600 dark:text-gray-400 mt-1">
        Confidential Medical Document
      </p>
    </div>
  </div>
</footer>
`;
}

/**
 * Gets template instructions for AI
 */
export function getTemplateInstructions(): string {
  return `
IMPORTANT: You must maintain the following HTML structure in your response:

1. HEADER: Always start with a header section using this exact structure:
   - Use the header classes: "bg-gradient-to-r from-blue-600 to-blue-700 text-white py-6 px-6 rounded-t-lg shadow-md"
   - Include: Report title, file name, file type, and analysis date
   - Format: Two-column layout (title on left, metadata on right)

2. MAIN CONTENT: Your analysis should be placed in the main section:
   - Use semantic HTML sections (<section> tags)
   - Suggested sections: Findings, Diagnosis, Recommendations, Observations
   - Each section should have an <h2> with classes: "text-2xl font-semibold text-gray-800 dark:text-gray-900 mb-4 border-b-2 border-blue-500 pb-2"
   - Use Tailwind CSS classes for styling
   - Structure content with proper spacing using: "space-y-4" or "space-y-6"
   - Use tables for structured data, lists for findings, and paragraphs for descriptions

3. FOOTER: Always end with a footer section:
   - Use classes: "bg-gray-100 dark:bg-slate-800 text-gray-700 dark:text-gray-300 py-4 px-6 rounded-lg mt-4 border-t-2 border-gray-300 dark:border-slate-600"
   - Include: Disclaimer text and report metadata
   - Two-column layout similar to header

Remember:
- Do NOT include <html>, <head>, or <body> tags
- Use Tailwind CSS utility classes throughout
- Maintain proper semantic HTML structure
- Ensure dark mode compatibility using dark: prefix classes
- Make tables responsive and well-formatted
- Use appropriate spacing and typography
`;
}

/**
 * Helper function to escape HTML
 */
function escapeHtml(text: string): string {
  const map: Record<string, string> = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#039;'
  };
  return text.replace(/[&<>"']/g, (m) => map[m]);
}

/**
 * Generates a simple report ID
 */
function generateReportId(): string {
  const timestamp = Date.now().toString(36);
  const random = Math.random().toString(36).substring(2, 7);
  return `${timestamp}-${random}`.toUpperCase();
}

